server:
  port: ${APLICATION_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${APP_DB_URL:localhost}:${APP_DB_PORT:5432}/${APP_DB_NAME:eatix_app}
    username: ${APP_DB_USERNAME:postgres}
    password: ${APP_DB_PASSWORD:nejra}
  jpa:
    hibernate:
      ddl-auto: update
    openInView: true
    show_sql: true
    generate-ddl: true
  data:
    jpa:
      repositories.enabled: true

service:
  ui:
    url: ${FRONTEND_API_URL:https://62a9ad66c63cd1719779bc3a--eatix.netlify.app/#/}

